mee/cpu.h
mee/drivers/riscv,cpu.h
src/cpu.c
src/drivers/riscv,cpu.c

Also add an API to get instruction length

Rename xx_exception_frame_pointer() APIs to exception_pc

---

Makefile.am
mee/button.h
mee/drivers/riscv,cpu.h
mee/drivers/sifive,global-external-interrupts0.h
mee/drivers/sifive,gpio-buttons.h
mee/drivers/sifive,gpio-leds.h
mee/drivers/sifive,gpio-switches.h
mee/drivers/sifive,gpio0.h
mee/drivers/sifive,local-external-interrupts0.h
mee/led.h
mee/switch.h
src/button.c
src/cpu.c
src/drivers/riscv,cpu.c
src/drivers/sifive,global-external-interrupts0.c
src/drivers/sifive,gpio-buttons.c
src/drivers/sifive,gpio-leds.c
src/drivers/sifive,gpio-switches.c
src/drivers/sifive,gpio0.c
src/drivers/sifive,local-external-interrupts0.c
src/interrupt.c
src/led.c
src/switch.c

Also extend gpios drivers to driver and turn LEDs on and off

Adding drivers support for leds, buttons and switches

---

mee/drivers/sifive,uart0.h
mee/uart.h
src/drivers/sifive,uart0.c

This is my proposed change to the UART API in #39 
Closes #39

Proposed change to UART API

---

mee/interrupt.h
src/drivers/sifive,gpio-buttons.c
src/drivers/sifive,gpio-switches.c
src/interrupt.c

This is my proposed change to the interrupt API in #37 
Closes #37

Proposed change to interrupt API

---

mee/cpu.h
mee/drivers/riscv,cpu.h
src/cpu.c
src/drivers/riscv,cpu.c
src/timer.c

This is my proposed change to the CPU timer API for #35 
Closes #35

Proposed change to CPU timer API

---

Makefile.am
Makefile.in
metal/drivers/sifive,gpio0.h
metal/gpio.h
src/drivers/sifive,gpio-leds.c
src/drivers/sifive,gpio0.c
src/gpio.c

I feel like the right public interface is on a per-pin basis, so I wrapped the existing internal driver to provide that.

Define a public API for GPIO output

---

metal/drivers/riscv,cpu.h
metal/drivers/riscv,plic0.h
src/drivers/riscv,cpu.c
src/drivers/riscv,plic0.c
src/drivers/sifive,global-external-interrupts0.c

While at it also fix a couple of PLIC interrupts indexing bugs

Enable floating point register saving for interrupt handler

---

src/drivers/sifive,uart0.c

This makes receiving data to actually work. Tested on HiFive 1 board.

Enable UART RX and fix getc

---

.github/CODEOWNERS

This will cause PRs to automatically request our review
@palmer-dabbelt Do you want added to the list too?

Add nategraff-sifive and bsousi5 as codeowners

---

Makefile.am
Makefile.in
metal/privilege.h
src/privilege.c

I added a struct for the entire register file, but for right now the privilege drop only sets `sp` and `ra`.

Add API for dropping to a lower privilege mode

---

src/drivers/sifive,fu540-c000,l2.c

Depends on sifive/freedom-devicetree-tools#56

Add constructor for FU540-C000 L2 cache controller

---

LICENSE

Add LICENSE, which is apache-2.0

---

src/drivers/riscv_clint0.c

The IPI example assumes that calling metal_cpu_software_set_ipi() will
quickly cause an interrupt when run against the current hart.  On
systems with longer bus latencies it may be possible to return before
the IPI becomes visible.  There is to way to guarantee the IPI occurs
before returning from this function, but we can at least account for the
variable bus latency by loading back the IPI register before returning.

drivers/riscv_clint0: Make IPIs blocking

---

src/pmp.c

Measuring the requested granularity of NAPOT regions had a fencepost
error. Create a second helper function instead of trying to repurpose
the same helper for detecting both the supported and requested
granularities.

Fix pmp granularity check for requested addresses

---

build.wake
scripts/autoconf_wrapper

This PR adds a wake file with rules for compiling freedom-metal and a helper script for running autoconf

add support for wake

---

src/drivers/sifive_fe310-g000_hfrosc.c
src/drivers/sifive_fe310-g000_hfxosc.c
src/drivers/sifive_fe310-g000_pll.c

Fixes warning on compile for targets with the FE310 PRCI

Fix PLL vtable const struct type

---

.gitignore
metal/cpu.h
metal/privilege.h

compiler warnings - not a prototype
expand gitignore

Compiler warnings & .gitignore improvement

---

metal/clock.h
metal/drivers/sifive_spi0.h
metal/drivers/sifive_uart0.h
src/clock.c
src/drivers/sifive_fe310-g000_pll.c
src/drivers/sifive_spi0.c
src/drivers/sifive_uart0.c

Build a linked list of clock callbacks to allow multiple to be registered.

Support multiple callbacks for a clock rate change

---

metal/tty.h
metal/uart.h
src/drivers/sifive_uart0.c
src/tty.c
src/uart.c

Adds polling functions for the UART interface.

Improve uart api

---

metal/gpio.h
src/drivers/sifive_gpio0.c
src/gpio.c

To test the new APIs, I add an example:
https://github.com/sifive/example-gpio

Add new APIs for GPIO input/interrupt functions

---

Makefile.am
Makefile.in
metal/drivers/sifive_fe310-g000_lfrosc.h
metal/drivers/sifive_wdog0.h
metal/watchdog.h
src/drivers/sifive_fe310-g000_lfrosc.c
src/drivers/sifive_wdog0.c
src/watchdog.c

Create a watchdog API and add a driver for sifive,wdog0 (sifive,aon0)
Also add a driver for FE310-G000 LFROSC.

Adds Watchdog API and drivers for sifive,wdog0 and FE310-G000 LFROSC

---

Makefile.am
Makefile.in
metal/drivers/sifive_fu540-c000_l2.h
src/drivers/sifive_fu540-c000_l2.c

These PR fix l2 cache controller compile failure.

Fix l2 cache controller compile failure

---

metal/cache.h
src/cache.c

metal_dcache_l1_discard()
metal_icache_l1_flush()
as well as for metal_icache_l1_available() to check availability of L1 I$

Add new APIs for CDISCARD and IFLUSH

---

src/drivers/riscv_cpu.c

It will get 0 without retry when mcycle overflow.

Retry if mcycle overflow when get cycle

---

src/init.c

This PR contains fix the issues as following:
1. It always return early when checking run once.
2. Didn't use address of symbols to compare start and end address.

Fix metal init issues

---

metal/spi.h
src/drivers/sifive_spi0.c

MULTI_WIRE_ALL
_                                                        _
CS     |______________________________________________________|
_   _   _   _   _   _   _   _   _   _   _   _   _   _
SCL    _| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_
Phase ---cmd--|-addr--|-dummy-|-data----------------------------
DQ0     0   4 | 0   4 | 0   4 | 0   4   8  12...
|       |       |
DQ1     1   5 | 1   5 | 1   5 | 1   5   9  13...
|       |       |
DQ2     2   6 | 2   6 | 2   6 | 2   6  10  14...
|       |       |
DQ3     3   7 | 3   7 | 3   7 | 3   7  11  15...
MULTI_WIRE_ADDR_DATA
_                                                        _
CS     |______________________________________________________|
_   _   _   _   _   _   _   _   _   _   _   _   _   _
SCL    _| |_| |_| |_| |_| |_| …

[v19.08 Backport] Add MULTI_WIRE mode and update spi driver.

---

Makefile.am
Makefile.in
metal/interrupt.h
src/drivers/riscv_clint0.c
src/drivers/riscv_cpu.c
src/vector.S

Commit to master, with review comment to use macro for vector interrupt handler

Enable clint vector support, plus exposing local interrupts vector handler

---

Makefile.am
Makefile.in
metal/atomic.h
src/atomic.c

Example in [freedom-e-sdk#391](https://github.com/sifive/freedom-e-sdk/pull/391)

Add Atomic API

---

src/drivers/riscv_plic0.c
src/drivers/sifive_clic0.c
src/entry.S

Recommit the changes, but without error out on ire larger than number of configure interrupts

Disable all plic and clic interrupts on init and feature register

---

src/privilege.c

Signed-off-by: Emmanuel Puerto <emmanuel.puerto@sifive.com>

Fix test condition into metal_privilege_drop_to_mode function

---

gloss/crt0.S
src/entry.S

SP 64bit alignment is now checked in crt0.S

ESAT-213 fix

---

src/drivers/sifive_spi0.c

Fix the swapped polarity/phase configuration and chip select settings for the SPI.
Fixes #218  #219

Fix SPI polarity/phase and chip select

---

src/drivers/sifive_spi0.c

Fix the swapped polarity/phase configuration and chip select settings for the SPI.

[v19.08 Backport] Fix SPI polarity/phase and chip select

---

metal/atomic.h
metal/compiler.h

But make it static inline this time.

Add back atomic API

---

gloss/sys_times.c

Now that the underlying functions are available, we can add the
times implementation by switching the functions it uses.

Re-add 'times' implementation

---

metal/hpm.h
src/hpm.c

Includes 64-bit event selectors from #272

Refactor HPM API

---

metal/privilege.h
metal/riscv.h
src/privilege.c

Change the register file type to use riscv_xlen_t/riscv_flen_t from metal/riscv.h and use MSTATUS fields from metal/riscv.h

Add back Privilege API to freedom-metal-next

---

.dir-locals.el

Add emacs init file to set indentation

---

metal/i2c.h
sifive-blocks/metal/drivers/sifive_i2c0.h
sifive-blocks/src/drivers/sifive_i2c0.c
sifive-blocks/templates/MANIFEST.ini
sifive-blocks/templates/metal/generated/sifive_i2c0.h.j2
sifive-blocks/templates/metal/machine/sifive_i2c0.h.j2
templates/metal/generated/i2c.h.j2

Add I2C driver back in

---

metal/pwm.h
sifive-blocks/metal/drivers/sifive_pwm0.h
sifive-blocks/src/drivers/sifive_pwm0.c
sifive-blocks/src/drivers/sifive_spi0.c
sifive-blocks/templates/MANIFEST.ini
sifive-blocks/templates/metal/generated/sifive_pwm0.h.j2
sifive-blocks/templates/metal/machine/sifive_pwm0.h.j2
templates/metal/generated/pwm.h.j2

Add PWM drivers

---

build.wake

build: remove unused function

---

.travis.yml
scripts/check-format
scripts/codegen.py
scripts/format

Enforce a uniform Python code format with the 'black' code formatter.

Use 'black' to format code generator Python script

---

src/drivers/sifive_fe310-g000_pll.c

Use labs() to compute abs() of long

---

Makefile.am
Makefile.in
configure
configure.ac
metal/time.h
segger/SEGGER_SEMIHOST.h
segger/SEGGER_target_metal.c
src/time.c
src/timer.c

Rebases #268 onto master and adds fixes for strict compiler warnings.

Add support for Segger libc

---

metal/cpu.h
scripts/codegen.py
scripts/format

Signed-off-by: Nathaniel Graff <nathaniel.graff@sifive.com>

Fix formatting

---

src/drivers/sifive_ccache0.c

Fix bug in sifive_ccache0_get_config().

Fix config data read error.

---

metal/drivers/sifive_hca1_regs.h

Apply change into register definition to feat with HCA ip fix

Fix register definition issue for HCA

---

Makefile.am
Makefile.in
metal/nmi.h

Add RNMI support
Signed-off-by: Frank Chang <frank.chang@sifive.com>

Add RNMI support

---

Makefile.am
Makefile.in
metal/drivers/sifive_remapper2.h
metal/remapper.h
src/drivers/sifive_remapper2.c
src/remapper.c

Add SiFive TileLink Address Remapper driver

Add SiFive TileLink Address Remapper driver

---

Makefile.am
Makefile.in
metal/drivers/sifive_l2pf1.h
metal/drivers/sifive_remapper2.h
metal/remapper.h
src/drivers/sifive_l2pf1.c
src/drivers/sifive_remapper2.c
src/init.c
src/remapper.c

* Add L2 Stride Prefetcher driver.
* Initialize L2 Stride Prefetcher during boot time if SPF exists.

Add L2 Stride Prefetcher support

---

Makefile.am
Makefile.in
metal/drivers/sifive_prci0.h
metal/prci.h
src/drivers/sifive_prci0.c
src/prci.c

This driver initializes some necessary PLLs.

Add sifive prci support for SiFive HiFive platform

---

src/drivers/sifive_ccache0.c

verify that BSS section is not into part of the LIM use for Cache

bacport PR#402

---

src/drivers/sifive_ccache0.c

(cherry picked from commit 61cc14da547f8bd57edfe6bc60ef3a7c9bc5a730)

Fix: remove warning

---

metal/drivers/sifive_pl2cache0.h
src/drivers/sifive_ccache0.c
src/drivers/sifive_pl2cache0.c
src/init.c

add init function to manage cleanEvictEnable bit, and modify ccache0 accordingly

pl2cache: fix

---

metal/drivers/sifive_pl2cache0.h
src/drivers/sifive_pl2cache0.c

(cherry picked from commit e89dacd46ce1cdab3c4efadabd151f8e940263fb)

sifive_pl2cache0: fix error
