Makefile.am
Without this users can't actually use the MEE environment as they won't
be able to link anything.
=> Install the linker scripts along with the archives

Makefile.am, mee/shutdown.h, mee/uart.h, src/clock.c, src/shutdown.c, src/uart.c
This allows these small functions to be inlined into user code if the
compiler chooses to do so, while also providing definitions in case the
compiler doesn't want to inline them.
=> Use "extern inline" for all inline functions

mee/compiler.h, src/drivers/sifive,fe310-g000,pll.c
This avoids a compilation warning.
=> Use the "abs()" from <stdlib.h>

Makefile.am, Makefile.in, gloss/crt0.S, mee/itim.h
Adds support to `gloss/crt0.S` for copying the `.itim` section into the ITIM memory.
Adds `mee/itim.h` for library support for interacting with the ITIM. To start with, define the macro `MEE_PLACE_IN_ITIM` which decorates functions to place in the ITIM.
=> Add support for ITIM

mee/itim.h
ITIM sections are placed in .itim, not .text.itim. This enables the
linker script to pull in the .text.* sections without pulling in the .itim
sections.
=> Fix ITIM linking

mee/drivers/sifive,global-external-interrupts0.h, mee/drivers/sifive,local-external-interrupts0.h, src/drivers/riscv,cpu.c, src/drivers/riscv,plic0.c, src/drivers/sifive,global-external-interrupts0.c, src/drivers/sifive,local-external-interrupts0.c
While at it also ensure init of local-interrupt, global-interrupt only done once
=> Add local interrupt enable/disable

Makefile.am, Makefile.in, doc/sphinx/classes/pmp.rst, doc/sphinx/index.rst, mee/pmp.h, src/pmp.c
Driver for PMP configuration which uses __riscv_xlen to determine which pmpcfgX CSRs to configure without requiring vtable lookups.
=> Add Support for PMP Configuration (No vtable version)

gloss/sys_sbrk.c
Improves the implementation of `sbrk()`:
- Return NULL when the difference between `mee_segment_heap_target_end` and `mee_segment_heap_target_start` == 0, indicating that no heap space has been allocated.
- Don't move the break past the end of the heap
=> Support 0-size heaps and check heap bounds

.gitattributes
Marks autotools-generated files as generated and the m4 support files as vendored so that they don't contribute to the language stats for the project.
=> Add .gitattributes to fix language stats

gloss/crt0.S
Replaces the t3 register with a0 so that crt0.S is compatible with both
the I and E base integer ISA.
=> Make crt0.S compatible with RV32E

src/drivers/sifive,fe310-g000,pll.c
This change saves us 0x880 (2176) bytes of RAM.
=> Make pll_configs const

Makefile.am, Makefile.in, doc/sphinx/apiref/lock.rst, metal/compiler.h, metal/lock.h, src/lock.c, src/trap.S
@palmer-dabbelt  This will fail to compile on targets without the atomic extension with an error like:
```
freedom-e-sdk/freedom-metal/src/lock.c: Assembler messages:
freedom-e-sdk/freedom-metal/src/lock.c:18: Error: unrecognized opcode `amoswap.w.aq a5,a5,(a4)'
freedom-e-sdk/freedom-metal/src/lock.c:29: Error: unrecognized opcode `amoswap.w.rl x0,x0,(a5)'
```
What do you think is the correct solution here? If there's a way to detect the arch with the preprocessor that would probably be ideal.
Closes #76
=> Create a public atomic lock API

Makefile.am, Makefile.in, gloss/crt0.S, metal/cpu.h, metal/drivers/fixed-factor-clock.h, metal/drivers/riscv,clint0.h, metal/drivers/riscv,plic0.h, src/cpu.c, src/drivers/fixed-factor-clock.c, src/drivers/riscv,clint0.c, src/drivers/riscv,cpu.c, src/drivers/riscv,plic0.c
Depends on #77 and #56
PR contains:
- crt0 defines a weak `secondary_main` which can be redefined by the user to startup secondary harts
- PLIC and CLINT modified to support multiple parent interrupt controllers
- A driver for fixed-factor-clock (Used in the HiFive Unleashed)
- A public API for querying the current hartid and the total number of harts
=> Multicore Support

metal/lock.h, src/lock.c
Declaring the functions inline in the header and defining them in the
source file was breaking the linker. Define and declare the functions in
the header and declare them extern inline in the source file.
=> Fix inlining of Metal Lock API

src/drivers/riscv,cpu.c
Certain targets which support Supervisor mode start without the
satp.MODE field cleared, resulting in enabled address translation. To
support User and Supervisor-mode bare-metal code without address
translation by default, clear the satp register at interrupt controller
init.
=> Clear satp on CPU interrupt controller init

metal/pmp.h, src/pmp.c
Detect target PMP granularity at PMP initialization.
Fail attempts to configure PMP regions when the requested granularity is smaller than the supported size.
=> Detect target PMP granularity

Makefile.am, Makefile.in, configure, configure.ac, metal/machine.h
Copy the machine header directly into `metal/machine.h` instead of `metal/machine/@MACHINE_NAME@.h`.
=> Remove indirection from metal/machine.h

Makefile.am, Makefile.in, metal/pmp.h, src/pmp.c
Also fixes the missing FU540 L2 driver headers, which might have gotten broken in the churn.
=> Use per-cpu PMP region count and granularity

src/drivers/sifive_clic0.c, src/drivers/sifive_test0.c
These two changes got overlooked earlier and were causing build-time warnings.
=> Fix some build-time warnings

src/entry.S
We've generated __metal_chicken_bit from freedom-devicetree-tools.
__metal_chicken_bit is used to enable/disable the predication feature on bullet series.
=> Enable chicken bit by writing 0 to 0x7c1.

src/drivers/sifive_spi0.c
Modified `src/drivers/sifive,spi0.c` only. Changed some of the preprocessor directives to match those specified in [SiFive FE310-G002 Manual v19p05](https://sifive.cdn.prismic.io/sifive%2F59a1f74e-d918-41c5-b837-3fe01ba7eaa1_fe310-g002-manual-v19p05.pdf).
Another thing to note is that I moved the CS deassert line to only after the RXDADA FIFO has been dequeued. There are some timing issues (according to Logic analyzer) if the CS# was immediately deasserted after the last byte in TXDATA was enqueued in the sending FIFO. Placing the deassert line so late in the process probably hurt performance a bit. I need to be able to get the SCK frequency in order to calculate a better latency, and this relates to the next point.
Any `set_baud_rate` doesn't seem to modify SPI clock rates at all. The …
=> Qspi debug

Makefile.am, Makefile.in, gloss/crt0.S, gloss/synchronize_harts.c
Use the MSIP registers in the CLINT or CLIC to make all harts wait for hart 0 to finish initializing the data section, BSS, and constructors.
=> Synchronize harts before calling secondary_main

gloss/crt0.S
crt0.S initializes the data, itim, and bss segments in memory on 64-bit targets using store/load double-words.
This is one of the changes necessary to remedy errors related to software failures on targets with ECC.
=> crt0 copies double-words on 64-bit targets

gloss/crt0.S
Ensure that the ITIM initialization is complete before fetching more instructions.
=> Add a fence after initializing the ITIM in crt0.S

metal/cpu.h, src/drivers/riscv_cpu.c
Only changes the internal method name in the CPU vtable
=> Rename CPU internal method from timer_get to mcycle_get

build.wake, scripts/autoconf_wrapper
Makes outputs of the `freedom-metal` compile job reproducible and adds a missing argument.
=> fix bugs in build.wake

src/drivers/sifive_test0.c, src/tty.c
Pass device handle to __metal_driver_sifive_test0_base().
Also fix type signature of nop_putc() and friends.
=> Fix sifive,test0 inline

metal/gpio.h
It uses `metal_interrupt` but doesn't include `interrupt.h`.
=> Explicitly include interrupt.h in gpio.h

doc/sphinx/devguide/exceptions.rst, doc/sphinx/devguide/interrupts.rst
There is no metal_get_cpu API. The real API name should be
metal_cpu_get
Signed-off-by: Zong Li <zong.li@sifive.com>
=> Correct the API name in document

metal/drivers/riscv_cpu.h
There is no user to use __metal_driver_interrupt_controller_vtable in riscv_cpu.h.
=> Remove unused structure in riscv_cpu.h

gloss/synchronize_harts.c
Make sure that _synchronize_harts() is in .init instead of .text to make
sure that it doesn't get placed in the ITIM. It must be linked into the
ROM so that it's available even before the ITIM is initialized.
=> Link _synchronize_harts() into .init

gloss/synchronize_harts.c
Make sure that _synchronize_harts() is in .init instead of .text to make
sure that it doesn't get placed in the ITIM. It must be linked into the
ROM so that it's available even before the ITIM is initialized.
=> Link _synchronize_harts() into .init [v201905 backport]

metal/pmp.h, src/pmp.c
Add these APIs because opensbi need these APIs to get the device information. The number of pmp regions and baud rate of UART could be hard coded in opensbi but it seem that provided by freedom-metal would be better.
=> Add to get number of PMP regions

Makefile.am, Makefile.in, metal/time.h, src/drivers/sifive_spi0.c, src/time.c
Add metal_time for internal use. In spi driver, it use the time() of libc, but we shouldn't expect user would link c library. It would cause the link error when user doesn't link libc.
=> Metal time

Makefile.am, Makefile.in, gloss/crt0.S, src/synchronize_harts.c
I want to use this from another C library that isn't based on libgloss.
=> Move _synchronize_harts from lmetal-gloss to lmetal

metal/drivers/riscv_cpu.h, metal/drivers/sifive_clic0.h, metal/interrupt.h, src/drivers/riscv_cpu.c, src/drivers/sifive_clic0.c, src/drivers/sifive_local-external-interrupts0.c, src/interrupt.c
This require the addition of these New interrupts APIs:
- metal_interrupt_set_vector_mode()
- metal_interrupt_get_vector_mode()
- metal_interrupt_set_privilege()
- metal_interrupt_get_privilege()
- metal_interrupt_set()
- metal_interrupt_clear(()
- metal_interrupt_register_vector_handler()
metal_interrupt_vector_enable() was fixed to removed the mode argument.
=> New APIs to better configure and manage CLIC interrupts

build.wake, scripts/autoconf_wrapper
the PR is to merge the same branch from https://github.com/sifive/freedom-metal/pull/124 into the v201905 branch
Makes outputs of the `freedom-metal` compile job reproducible and adds a missing argument.
=> add wake build rule fixes to v201905

gloss/crt0.S, src/drivers/riscv_cpu.c
Only initialize the data of metal_interrupt structure in initail
function of interrupt controller. Separate the CSR initialization into
startup code would be more clear.
The setting FS bits of mstatus is present already in startup code, we
just add the setting of mie, mip, mideleg, medeleg and satp here.
Signed-off-by: Zong Li <zong.li@sifive.com>
=> Move initializing CSRs to startup code

src/drivers/sifive_spi0.c
Backports #160 to v201908-branch
=> [19.08 Backport] Fixed the cs pin assignment.

src/drivers/sifive_spi0.c
The programming issue is found when using ESP-SOLO as SPI slave device. The chip select pin is SPI_CS_2.
=> Fixed the cs pin assignment.

src/synchronize_harts.c
metal_cpu_get_current_hartid() might be in the ITIM and is not available
at the time that synchronize_harts() is called. Use inline assembly
instead.
=> Don't call metal API in synchronize_harts()

src/synchronize_harts.c
metal_cpu_get_current_hartid() might be in the ITIM and is not available
at the time that synchronize_harts() is called. Use inline assembly
instead.
=> [19.08 Backport] Don't call metal API in synchronize_harts()

src/drivers/sifive,htif0.c
Return the exit code to spike.
=> Update HTIF shutdown func.

gloss/sys_sbrk.c
newlib will check the return value, it treat -1 as error, return NULL or just set it to end will made newlib thought it succeeded and then continue to use those region, that's might cause memory corruption on other memory region.
=> Return (void *)-1 on error for sbrk

gloss/sys_sbrk.c
- newlib will check the return value, it treat -1 as error,
return NULL or just set it to end will made newlib thought it
succeeded and then continue to use those region, that's might
cause memory corruption on other memory region.
=> [19.08 Backport] Return (void *)-1 on error for sbrk

Makefile.am, Makefile.in, doc/sphinx/apiref/init.rst, doc/sphinx/devguide/init.rst, gloss/crt0.S, metal/init.h, src/drivers/sifive_fe310-g000_pll.c, src/drivers/sifive_fu540-c000_l2.c, src/init.c, src/tty.c
This creates the Metal Init API for defining constructors and destructors to run before main/upon exit, both within Metal drivers and in user application code.
This also allows users to disable constructors/destructors from running automatically by redefining the following functions in their application:
```
void metal_init_run(void) {}
void metal_fini_run(void) {}
```
Users can then call `metal_init()` and `metal_fini()` at their leisure to run Metal constructors/destructors.
Depends on [freedom-devicetree-tools#149](https://github.com/sifive/freedom-devicetree-tools/pull/149).
=> Create Metal Init API

Makefile.am, Makefile.in, src/drivers/riscv_cpu.c, src/entry.S, src/trap.S
We got some discussion on #161 . In some cases, when user call the interrupt initial API, it would overwrite the mtvec which holds the user's trap handler.
These patches contains adding the condition for the mtvec assignment, and separating early_trap_vector to trap.S to ensure that we only link the stuff we needed.
=> Fix mtvec overwrite

Makefile.am, Makefile.in, metal/drivers/sifive_trace.h, src/drivers/sifive_trace.c
Adds UART driver for the SiFive Nexus Trace Encoder to support use with stdout-path.
=> [v19.08 Backport] Trace encoder UART driver

Makefile.am, Makefile.in, metal/drivers/sifive_trace.h, src/drivers/sifive_trace.c
Add support to freedom-metal to allow redirecting stdout to use the trace-encoder as the stdout device instead of the UART. This allows printing into the trace message stream as Aux Access Write Message trace messages, which the trace-deocoder can reconstruct into the printed messages.
=> Trace encoder putc() support

metal/spi.h, src/drivers/sifive_spi0.c
QSPI_ALL
_                                                        _
CS     |______________________________________________________|
_   _   _   _   _   _   _   _   _   _   _   _   _   _
SCL    _| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_
Phase ---cmd--|-addr--|-dummy-|-data----------------------------
DQ0     0   4 | 0   4 | 0   4 | 0   4   8  12...
|       |       |
DQ1     1   5 | 1   5 | 1   5 | 1   5   9  13...
|       |       |
DQ2     2   6 | 2   6 | 2   6 | 2   6  10  14...
|       |       |
DQ3     3   7 | 3   7 | 3   7 | 3   7  11  15...
QSPI_ADDR_DATA
_                                                        _
CS     |______________________________________________________|
_   _   _   _   _   _   _   _   _   _   _   _   _   _
SCL    _| |_| |_| |_| |_| |_| |_| |_| |_| …
=> Add QSPI mode and update spi driver.

metal/interrupt.h, src/drivers/riscv_plic0.c, src/interrupt.c
This patchset contains the supporting multi-core of PLIC driver. It should calculate the offset by hart context id to access the relevant region of each hart.
It would use the new stuff in metal header files which generated by freedom-devicetree-tools [PR freedom-devicetree-tools](https://github.com/sifive/freedom-devicetree-tools/pull/150).
This patchset doesn't support the multi-core of CLIC driver. In the CLIC specification, the multicore systems might have a CLIC per-core, so CLIC driver need to more other changed.
We also need to modify all test programs in freedom-e-sdk/software. All test program has own git repository, I would push the modification respectively.
=> Support multi-core of PLIC driver

metal/drivers/sifive_clic0.h, metal/uart.h, src/drivers/sifive_uart0.c, src/uart.c
Added the following external APIs
int metal_uart_transmit_interrupt_enable(struct metal_uart *uart);
int metal_uart_transmit_interrupt_disable(struct metal_uart *uart)
int metal_uart_receive_interrupt_enable(struct metal_uart *uart);
int metal_uart_receive_interrupt_disable(struct metal_uart *uart);
int metal_uart_set_transmit_watermark(struct metal_uart *uart, size_t level);
size_t metal_uart_get_transmit_watermark(struct metal_uart *uart);
int metal_uart_set_receive_watermark(struct metal_uart *uart, size_t level);
size_t metal_uart_get_receive_watermark(struct metal_uart *uart);
=> Extend uart driver to support interrupt and watermark setting

metal/drivers/sifive_clic0.h
Back port a bug found in master, which customer may/have hit.
=> Aligned mtvt-table to 64bytes

src/entry.S
QEMU and Spike don't properly emulate this CSR and crash when we attempt
to clear it.
We can put this back when we have a solution that doesn't break our emulators, be that a workaround in devicetree tools or fixing the emulators.
=> Revert "Always clear feature disable register"

src/drivers/riscv_plic0.c, src/drivers/sifive_clic0.c
This breaks the CLIC driver, but we're reverting both for now to be safe.
=> Revert "Disable all plic and clic interrupts on init"

src/drivers/sifive_uart0.c
There's a spot in the uart vtable for this function, but it wasn't
getting initialized. That function didn't match the required API as it
was returning 1 when not blocked and 0 when blocked instead of 0 when
not blocked and non-zero when blocked.
=> Hook up txready in sifive_uart0

src/drivers/riscv_plic0.c, src/i2c.c
Fix warning as error issues when following options applied:
-std=c99 -Wall -Wextra -Werror -Wpedantic -Werror -Wno-unused-parameter
=> Fix warnings as error issues when following options applied

scripts/autoconf_wrapper
Fixes https://github.com/sifive/freedom-metal/issues/212.
Assuming that I correctly understand the problem, which I commented [here](https://github.com/sifive/freedom-metal/issues/212#issuecomment-572673009), I think this is just a one-character fix. The tl;dr is that when `autoconf_wrapper` was refactored to take in different arguments, the `if` statement at the top of the file wasn't updated with the new expected number of arguments.
Note that I have done absolutely zero testing of this, but I wanted to propose this PR to expedite the process of getting this fixed if it's the correct fix.
=> Update autoconf_wrapper argument parsing with correct number of arguments.

src/drivers/sifive_fe310-g000_pll.c
We want to clear the PLL_SEL bit iff it's set, so check if the value is nonzero before clearing.
Fixes #210
=> Fix PLL selector polarity check

src/drivers/sifive_fe310-g000_pll.c
We want to clear the PLL_SEL bit iff it's set, so check if the value is nonzero before clearing.
This fix needs backported so that it gets picked up on the current default branch. It shouldn't affect support for Core Designer because none of those targets have an FE310 PLL.
=> [v19.08 Backport] Fix PLL selector polarity check

metal/drivers/riscv_clint0.h, metal/drivers/sifive_clic0.h, src/drivers/sifive_fe310-g000_pll.c
The FE310 PLL needs 100 usec to stabilize before testing the lock signal. This solution assumes that mtime is driven at 32768 Hz for all targets with the FE310 PLL.
Should this be backported to v19.08?
Fixes #213
=> Wait 100usec before testing FE310 PLL for lock

gloss/sys_times.c
Move 'inline' before 'unsigned long long' instead of after to make GCC
happy.
=> When GCC is run with more pedantic flags, it needs 'inline' before type

src/drivers/sifive_trace.c
Resolves the warning when building Freedom Metal:
```
freedom-metal/src/drivers/sifive_trace.c:85:18: warning: initialization of 'int (*)(struct metal_uart *, int)' from incompatible pointer type 'int (*)(struct metal_uart *, unsigned char)' [-Wincompatible-pointer-types]
.uart.putc = __metal_driver_sifive_trace_putc,
```
=> Fix function signature for sifive,trace putc

sifive-blocks/src/drivers/sifive_fe310_g000_hfrosc.c, sifive-blocks/src/drivers/sifive_fe310_g000_hfxosc.c, sifive-blocks/src/drivers/sifive_fe310_g000_lfrosc.c, sifive-blocks/src/drivers/sifive_fe310_g000_pll.c, sifive-blocks/templates/MANIFEST.ini, sifive-blocks/templates/metal/generated/sifive_fe310_g000_hfrosc.h.j2, sifive-blocks/templates/metal/generated/sifive_fe310_g000_hfxosc.h.j2, sifive-blocks/templates/metal/generated/sifive_fe310_g000_lfrosc.h.j2, sifive-blocks/templates/metal/generated/sifive_fe310_g000_pll.h.j2, sifive-blocks/templates/metal/machine/sifive_aon0.h.j2, sifive-blocks/templates/metal/machine/sifive_fe310_g000_prci.h.j2
Instead of depending upon the devicetree nodes for the oscillators to point at specific memory locations in the PRCI/AON to describe their control registers, just define their registers explicitly in the platform header.
=> Use PRCI/AON registers for FE310 Oscillator Drivers

src/tty.c
Port of #271 to Freedom Metal refactor work.
Allows standard out to be extracted from an instruction trace when no
other stdio method is available.
=> Add a nop hint to nop_putc()

metal/button.h, metal/switch.h, sifive-blocks/src/drivers/sifive_gpio_buttons.c, sifive-blocks/src/drivers/sifive_gpio_switches.c, src/button.c, src/switch.c, templates/metal/generated/button.h.j2, templates/metal/generated/switch.h.j2
This creates defines for applications to use buttons and switches
by label. A DTS entry like:
button@0 {
compatible = "sifive,gpio-buttons";
label = "BTN0";
gpios = <&L12 4>;
interrupts-extended = <&L14 4>;
linux,code = "none";
};
creates definitions like this:
#define metal_button_btn0_interrupt_handler metal_sifive_gpio0_source_4_handler
#define metal_button_btn0 ((struct metal_button) { 0 })
In code, this allows the ISR to be declared like:
void metal_button_btn0_interrupt_handler (void);
and controlled with:
metal_button_enable_interrupt(but0);
...
metal_button_disable_interrupt(but0);
=> Add button/switch definitions that use labels

metal/cpu.h, metal/riscv.h, src/drivers/riscv_clint0.c, src/drivers/riscv_cpu.c, src/drivers/riscv_cpu_intc.c, src/drivers/riscv_plic0.c
Also makes interrupt enable/disables in the CPU API return void. Since they can operate only on the current hart, this also removes the `struct metal_cpu` parameter.
=> Add enable/disable for the external interrupt

metal/time.h, metal/timer.h, sifive-blocks/src/drivers/sifive_spi0.c
These just wrap existing functions in a different API, so make
them static inline instead of separate functions.
=> Add metal/time.h and metal/timer.h

metal/cache.h, sifive-blocks/metal/drivers/sifive_ccache0.h, sifive-blocks/src/drivers/sifive_ccache0.c, sifive-blocks/templates/MANIFEST.ini, sifive-blocks/templates/metal/machine/sifive_ccache0.h.j2, sifive-blocks/templates/metal/machine/sifive_fu540_c000_l2.h.j2, src/cache.c, templates/metal/generated/cache.h.j2
The L1 API remains in metal/cache.h
The SiFive L2 API is now driver-specific because an abstracted public API is unnecessary.
=> Refactor L1 and L2 Cache APIs

sifive-blocks/src/drivers/sifive_spi0.c, sifive-blocks/src/drivers/sifive_uart0.c
The clock rate change callbacks may happen before the drivers have
been initialized. In this case they need to be ignored. Check for this
case by looking for an uninitialized baud_rate.
=> Ignore clock rate changes before init in SPI/UART

metal/cpu.h, sifive-blocks/metal/drivers/sifive_buserror0.h, sifive-blocks/src/drivers/sifive_buserror0.c, sifive-blocks/templates/metal/generated/sifive_buserror0.h.j2, sifive-blocks/templates/metal/machine/sifive_buserror0.h.j2, src/drivers/riscv_cpu.c, src/exception.c, templates/metal/generated/riscv_cpu.h.j2, templates/metal/interrupt_handlers.h.j2, templates/src/interrupt_handlers.c.j2, templates/src/jump_table.S.j2
Among other things, this refactor also makes it so that the bus error unit local interrupt is properly vectored by HLIC hardware vectoring.
=> Refactor sifive,buserror0 driver

sifive-blocks/templates/metal/generated/sifive_aon0.h.j2
QEMU does not emulate the AON behavior, so it's valid for it to not
describe the parent clock or interrupt controller
=> Fix AON driver for QEMU E31

.travis.yml
We've been adding some CI to all Git repos with Wake installed so that we can get type checking.
I opted against doing the more sophisticated setup we have in some other repos because 1) this repo just has Pull Request CI set up with Travis CI and 2) this repo has no wit dependencies, so we don't necessarily need that boilerplate.
I hope you don't mind me just taking this on to the end of your Travis CI configuration. I'd be more than happy to port this to GitHub Actions.
=> Add CI check for Wake 0.19 syntax.

src/drivers/sifive_fe310-g000_pll.c
GCC 10 complains about possible integer truncation when passing a long int to abs().
=> Fix integer truncation on abs() call

.github/workflows/wake.yml, build.wake, scripts/codegen.py, templates/metal.mk.j2, tests/spike/core.dts, tests/spike/design.dts, tests/test-wake-api.sh, tests/test-wake-install.sh, wit-manifest.json
This series adds support for running Freedom Metal code generation in a wit/wake build environment.
In order to make this work, generated paths in metal.mk are now relative to the `ROOT_DIR` Make variable. This allows the delivered make fragment to be reusable outside of the Wake build environment.
=> Add Wake API for Freedom Metal code generation and installation

gloss/sys_fork.c, metal/cpu.h, sifive-blocks/templates/metal/private/metal_private_sifive_fe310_g000_pll.h.j2, src/drivers/riscv_plic0.c, src/pmp.c, src/synchronize_harts.c, templates/metal/interrupt_handlers.h.j2, templates/src/interrupt_handlers.c.j2
Functions taking no arguments should be defined using (void) instead
of () as the latter means 'unknown arguments' instead of 'no arguments'.
There was only one function declared using () which took a parameter,
__metal_exception_handler, which is defined to take 'riscv_xlen_t
mcause' but declared using ().
=> Fix old-style function declarations/definitions

metal/drivers/ucb_htif0.h, src/drivers/ucb_htif0.c, src/tty.c, templates/MANIFEST.ini, templates/metal/platform/metal_platform_ucb_htif0.h.j2, templates/metal/private/metal_private_ucb_htif0.h.j2
In addition to adding back the HTIF driver, we also add a weak alias for metal_tty_getc() so that targets without stdio can build with picolibc.
=> [next] Add support for ucb,htif0 for the Spike simulator

Makefile.am, Makefile.in, gloss/crt0.S, metal/drivers/sifive_ccache0.h, metal/lim.h, src/drivers/sifive_ccache0.c
Update cache driver _init() to not enable cache ways corresponding to L2 LIM region in use.
=> Add support for L2 LIM.

build.wake
Use wake's `here` self-reference variable to determine the relative path to the root of the freedom-metal repository
=> wake: use 'here' to provide base filesystem directory

build.wake
Wake's directory handling is a bit flawed, and you can run into situations where sometimes a build rule won't run correctly when an output directory is not passed in as a visible file to the `Plan`. The way to avoid any issues is to always call `mkdir` on the directory in Wake to produce a `Path` corresponding to the directory, and then passing that into the visible file list to a `Plan`.
I did this for the `runFreedomMetalInstall` function, since I was hitting issues trying to bump freedom-metal in api-generator-sifive.
=> build.wake: Ensure output directory is created before installing.

scripts/codegen.py
Freedom Metal has a single local interrupt table, so we only need to
enumerate the interrupts of a single instance of
sifive,local-external-interrupts0 in the code generator in order to get
the list of local interrupts.
=> Deduplicate local interrupt handlers

metal/cpu.h
This fixes a warning in the asserts added to the riscv,cpu-intc driver.
=> metal_cpu_get_current_hartid returns uint32_t

sifive-blocks/templates/metal/private/metal_private_sifive_pwm0.h.j2
**Issue Description**
PWM doesn't work well with example-pwm in freedom-metal-next branch.
There are missing comparator_count and compare_width fields in dt_pwm_data for PWM.
**Root Cause**
In core.dts, pwm node has following properties.
sifive,ncomparators
sifive,comparator-widthbits
But, j2 file includes the wrong item name. It needs to fix.
**Test**
example-pwm works well on sesame with vcu-118 fpga.
**Question**
I have another issue.
I'd like to test PWM interrupt, too. But it has only one interrupt_id in dt_pwm_data, though interrupts property in pwm node in core.dts file has 4 interrupt ids. Also, in sifive_pwm0.c, there is no API to get which interrupt index to enable/disable PWM interrupt.
I think it should also fix. Can I add the code for these issues?
=> Fix comparator_count and compare_width fields in dt_pwm_data for PWM

templates/metal/private/metal_private_gpio.h.j2
**Description**
In metal_private_gpio.h.j2,  template variable needs "_get_" for  get_intput/output_pin.
=> fix template file for metal_private_gpio.h

metal/pwm.h, sifive-blocks/src/drivers/sifive_pwm0.c, sifive-blocks/templates/metal/private/metal_private_sifive_pwm0.h.j2
**Issue Description**
PWM Interrupt doesn't work well with example-pwm in freedom-metal-next branch on [sesame.](url)
**Root Cause**
In sesame core.dts, the number of pwm interrupt channel ID is 4. pwm0 : 35, 36, 37, 38, pwm1 : 39, 40, 41, 42
```
L43: pwm@10020000 {
clocks = <&L39>;
compatible = "sifive,pwm0";
interrupt-parent = <&L3>;
interrupts = <35 36 37 38>;
reg = <0x0 0x10020000 0x0 0x1000>;
reg-names = "control";
sifive,comparator-widthbits = <16>;
sifive,ncomparators = <4>;
};
L44: pwm@10021000 {
clocks = <&L39>;
compatible = "sifive,pwm0";
interrupt-parent = <&L3>;
interrupts = <39 40 41 42>;
reg = <0x0 0x10021000 0x0 0x1000>;
reg-names = "control";
sifive,comparator-widthbits = <16>;
sifive,ncomparators = <4>;
};
```
But, the implement in j2 file considered the index only for …
=> Support to enable parent interrupt of PWM channel ID in metal_pwm_cfg_interrupt

gloss/crt0.S
argv may be unaligned depend on the context of rodata, then causes application occurs unaligned fault when paring argv
=> Fix crt0 passes unaligned argv to main()

gloss/crt0.S, src/entry.S, src/scrub.S, src/vector.S
- A symbol is either weak and global bind, declare a symbol with .weak
and .global will result weak binding only in binutils.
- But in LLVM, such kind of legacy usage is forbidden.
Ref: https://reviews.llvm.org/D90108
=> Fix clang build due to declare a symbol with both .weak and .global

configure, configure.ac
Help messsages for the following commands contained a typo:
- `--with-builtin-libgloss`
- `--with-builtin-libmetal-pico`
- `--with-builtin-libmetal-segger`
This commit fixes those.
configure.ac has been regenerated using autoconf 2.69.
=> configure.ac: Fix typo in help messages.

sifive-blocks/src/drivers/sifive_gpio0.c
**Issue Description**
I try to clear only one bit of the interrupt pending register.
But all the bits in register is cleared.
**Root Cause**
I checked "sifive_gpio0_clear_interrupt()" in sifive_gpio.c 
To clear a pending bit, there was "|= OR" operation like 
case METAL_GPIO_INT_RISING:
GPIO_REGW(METAL_SIFIVE_GPIO0_RISE_IP) |= (1 << pin);
break;
**Test**
After i  replaced  "|=" operation with "=" ,  this problem is cleared on fpga vcu118
Refer to : https://sifive.atlassian.net/servicedesk/customer/portal/64/IPOBHD-308
=> fix gpio interrupt clear bit control

src/init.c
add sifive_ccache0_init by default into metal_init function.
=> Add ccache0 init by default if ccache0 is present.

gloss/crt0.S
When initializing the vector unit (when present), boot code should also initialize `vstart`, `vxrm`, and `vxsat`; see [spec](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#state-of-vector-extension-at-reset).
Closes #375, which concerns a particular problem that may arise when this is not done.
=> Initialize V-extension CSRs

gloss/crt0.S
backport commit 79d0422c03d9828f8d083e160a556ffc71b35759
=> crt0: make argv 8-byte aligned

src/drivers/sifive_pl2cache0.c
(cherry picked from commit 966a62d6f1b1a0f654fe8efb004db588cc270001)
=> sifive_pl2cache0: fix missing hartid init

src/drivers/sifive_prci0.c
This PR gives some modifications as follows:
1. According to FSBL, the range field should be 3'b100 in 1 GHz.
2. Remove comment of range field, it is copied accidentally from Unmatched.
=> Fix typos in prci driver for Unleashed.

metal/drivers/sifive_l2pf0.h
The structure "sifive_l2pf0_config" in "sifive_l2pf0.h" header file was not matching "U74 L2 Hardware Prefetcher" document, revision dated of  01/28/2021. Naming and addresses of registers were not accurate any more. Their bits description were not accurate.
=> Header file "sifive_l2pf0.h" updated according to "U74 L2 Hardware Prefetcher" document

gloss/sys_write.c
`_write` is returning `0` instead of the expected number of characters written.
One of the consequences is that
```
printf("string1\nstring2\n")
```
will only output:
```
string1\n
```
because `printf` will abort after the first `_write` call.
This was fixed by @loiclefort on a downstream (private) fork, but that fix was apparently never upstreamed. It was reported recently in the SiFive forums: https://forums.sifive.com/t/some-freedom-studio-qemu-annoyances/5561
=> Fix issue with gloss _write function
